CREATE TABLE DEPARTMENT (
UID_DEPARTMENT BIGINT NOT NULL,
NAME VARCHAR(200) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL
);

COMMENT ON TABLE DEPARTMENT IS 'Tabela com os departamentos da empresa.';
COMMENT ON COLUMN DEPARTMENT.UID_DEPARTMENT IS 'Identificador único da tabela DEPARTMENT.';
COMMENT ON COLUMN DEPARTMENT.NAME IS 'Nome do departamento.';
COMMENT ON COLUMN DEPARTMENT.CREATED_AT IS 'Data de criação do department.';