CREATE SEQUENCE SEQUENCE_PRODUCT START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCT (
    UID_PRODUCT BIGINT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(400) NOT NULL,
    PRICE NUMERIC(10,2) NOT NULL,
    FK_DEPARTMENT_UID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY(UID_PRODUCT);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_UID_DEPARTMENT FOREIGN KEY (FK_DEPARTMENT_UID) REFERENCES DEPARTMENT (UID_DEPARTMENT);

COMMENT ON TABLE PRODUCT IS 'Tabela com os produtos da empresa.';
COMMENT ON COLUMN PRODUCT.UID_PRODUCT IS 'Identificador único da tabela PRODUCT.';
COMMENT ON COLUMN PRODUCT.NAME IS 'Nome do produto.';
COMMENT ON COLUMN PRODUCT.CODE IS 'Codigo do produto.';
COMMENT ON COLUMN PRODUCT.DESCRIPTION IS 'Descrição do produto.';
COMMENT ON COLUMN PRODUCT.PRICE IS 'Preço do produto.';
COMMENT ON COLUMN PRODUCT.FK_DEPARTMENT_UID IS 'Chave estrangeira referenciando o UID do departamento.';
COMMENT ON COLUMN PRODUCT.CREATED_AT IS 'Data de criação do produto.';