CREATE SEQUENCE SEQUENCE_PROMOTION START WITH 1 INCREMENT BY 1;

CREATE TABLE PROMOTION (
    UID_PROMOTION BIGINT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    BEGIN_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(400) NOT NULL,
    DISCOUNT NUMBER(10,2) NOT NULL,
    FK_COMPANY_UID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

ALTER TABLE PROMOTION ADD CONSTRAINT PK_PROMOTION PRIMARY KEY(UID_PROMOTION);
ALTER TABLE PROMOTION ADD CONSTRAINT FK_PROMOTION_UID_COMPANY FOREIGN KEY (FK_COMPANY_UID) REFERENCES COMPANY (UID_COMPANY);

COMMENT ON TABLE PROMOTION IS 'Tabela com as promoções da empresa.';
COMMENT ON COLUMN PROMOTION.UID_DEPARTMENT IS 'Identificador único da tabela PROMOTION.';
COMMENT ON COLUMN PROMOTION.NAME IS 'Nome da promoção.';
COMMENT ON COLUMN PROMOTION.BEGIN_DATE IS 'Data de início da promoção.';
COMMENT ON COLUMN PROMOTION.END_DATE IS 'Data de fim da promoção.';
COMMENT ON COLUMN PROMOTION.DESCRIPTION IS 'Descrição da promoção.';
COMMENT ON COLUMN PROMOTION.DISCOUNT IS 'Valor do desconto da promoção.';
COMMENT ON COLUMN PROMOTION.FK_COMPANY_UID IS 'Chave estrangeira referenciando o UID da empresa.';
COMMENT ON COLUMN PROMOTION.CREATED_AT IS 'Data de criação da promoção.';
