CREATE SEQUENCE SEQUENCE_DELIVERY START WITH 1 INCREMENT BY 1;

CREATE TABLE DELIVERY (
    UID_DELIVERY BIGINT NOT NULL,
    REGION VARCHAR(200) NOT NULL,
    PRICE NUMERIC(10,2) NOT NULL,
    FK_COMPANY_UID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY PRIMARY KEY(UID_DELIVERY);
ALTER TABLE DELIVERY ADD CONSTRAINT FK_DELIVERY_UID_COMPANY FOREIGN KEY (FK_DELIVERY_UID) REFERENCES COMPANY (UID_COMPANY);

COMMENT ON TABLE DELIVERY IS 'Tabela de frete da empresa.';
COMMENT ON COLUMN DELIVERY.UID_DELIVERY IS 'Identificador único da tabela DELIVERY.';
COMMENT ON COLUMN DELIVERY.REGION IS 'Nome da região da entrega.';
COMMENT ON COLUMN DELIVERY.PRICE IS 'Valor da entrega.';
COMMENT ON COLUMN DELIVERY.FK_COMPANY_UID IS 'Chave estrangeira referenciando o UID da empresa.';
COMMENT ON COLUMN DELIVERY.CREATED_AT IS 'Data de criação do frete.';